name: dart_clang
description: Clang bindings for Dart lang.
version: 1.0.0
authors:
  - Harshal Nandigramwar <pro.bbcom18@gmail.com>
homepage: https://bitbeast18.github.io/dart_clang

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ffi: ^0.1.3


dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
